language: csharp
solution: HtcSharp.sln
mono: none
dotnet: 3.0
dist: bionic
script:
 - dotnet restore
 - dotnet build
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1